management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  forward-headers-strategy: framework

mas:
  paths:
    inventory: scripts/inventory.ini
    playbooks: scripts
  bootstrap:
    group: bootstrap
    public-key: ~/.ssh/id_ed25519.pub